name: Generate ID list
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  generate-page-ids:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5 
        with:
          python-version: '3.12.1'
      - run: pip install requests
      - run: python idscrape.py
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: ./gradlew build
      - run: ./gradlew run
      - uses: actions/upload-artifact@v4
        with:
          path: |
            page_ids.h2.mv.db
            obj_ids.txt
            npc_ids.txt
          name: scraper-outputs
  commit-files-to-repo:
    runs-on: ubuntu-latest
    needs: generate-page-ids
    steps:
      - uses: actions/checkout@v4
        with:
          ref: db
      - uses: actions/download-artifact@v4
        with:
          name: scraper-outputs
      - run: |
          git config --global user.name 'bigdiesel2m'
          git config --global user.email 'bigdiesel2m@users.noreply.github.com'
          git add .
          git commit -m "Database update: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
